### ISSUE TITLE
exports.function throws error in IE9

### ISSUE THREAD

**Issue by projectnard** [zenorocha/good-listener#4]
IE9 doesnt support named parameteres that are also keywords. So in src/is.js, line 45 throws and error.

`exports.function = {}`

**Comment by zenorocha** [comment]
Could you send a PR?

**Comment by benjifs** [comment]
I sent a pull request on behalf of bvferguson to fix this issue

**Comment by zenorocha** [comment]
Fixed in #5. Thanks for reporting @bvferguson!

**Comment by Craga89** [comment]
As of `1.1.5` the dist files are now broken, due to the `is` module exporting `function`

https://github.com/zenorocha/good-listener/blob/v1.1.5/dist/good-listener.js#L144

But the main module is using `is.fn`:

https://github.com/zenorocha/good-listener/blob/v1.1.5/dist/good-listener.js#L172

**Comment by benjifs** [comment]
Just sent in a PR to address this issue
